export default {
  LOAD_POKEDEX: "LOAD_POKEDEX",
  POKEDEX_LOADED: "POKEDEX_LOADED",
  POKEDEX_LOAD_ERROR: "POKEDEX_LOAD_ERROR",

  LOAD_CAUGHT_POKEMON: "LOAD_CAUGHT_POKEMON",

  LOAD_POKEMON: "LOAD_POKEMON",
  CATCH_POKEMON: "CATCH_POKEMON",
  POKEMON_LOAD_ERROR: "POKEMON_LOAD_ERROR"
}